services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:8000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - GATEWAY_DB_HOST=${GATEWAY_DB_HOST}
      - GATEWAY_DB_NAME=${GATEWAY_DB_NAME}
      - GATEWAY_DB_USER=${GATEWAY_DB_USER}
      - GATEWAY_DB_PASS=${GATEWAY_DB_PASS}
      - GATEWAY_DB_PORT=${GATEWAY_DB_PORT}
    volumes:
      - ./api-gateway:/code
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      gateway-db:
        condition: service_healthy
    networks:
      - notify_network
      
  gateway-db:
    image: postgres:15-alpine
    hostname: gateway-db
    environment:
      - POSTGRES_DB=${GATEWAY_DB_NAME}
      - POSTGRES_USER=${GATEWAY_DB_USER}
      - POSTGRES_PASSWORD=${GATEWAY_DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    networks:
      - notify_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GATEWAY_DB_USER} -d ${GATEWAY_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notify_network

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notify_network
      
networks:
  notify_network:
    driver: bridge

volumes:
  gateway_db_data:
    driver: local