services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:8000"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - GATEWAY_DB_HOST=${GATEWAY_DB_HOST}
      - GATEWAY_DB_NAME=${GATEWAY_DB_NAME}
      - GATEWAY_DB_USER=${GATEWAY_DB_USER}
      - GATEWAY_DB_PASS=${GATEWAY_DB_PASS}
      - GATEWAY_DB_PORT=${GATEWAY_DB_PORT}
    volumes:
      - ./api-gateway:/code
    depends_on:
      - rabbitmq
      - redis
      - gateway-db
    networks:
      - notify_network
  gateway-db:
    image: postgres:15-alpine
    hostname: gateway-db
    environment:
      - POSTGRES_DB=${GATEWAY_DB_NAME}
      - POSTGRES_USER=${GATEWAY_DB_USER}
      - POSTGRES_PASSWORD=${GATEWAY_DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - gateway_db_data:/var/lib/postgresql/data
    networks:
      - notify_network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${GATEWAY_DB_USER} -d ${GATEWAY_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notify_network
  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notify_network
  template-service:
    build:
      context: ./template-service
    container_name: template-service
    env_file:
      - ./.env
    ports:
      - "${TEMPLATE_SERVICE_PORT}:8002"
    environment:
      - NODE_ENV=production
      - TEMPLATE_SERVICE_PORT=8002
    networks:
      - notify_network
    depends_on:
      template-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8002",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  template-db:
    image: postgres:15-alpine
    container_name: template-db
    environment:
      POSTGRES_DB: ${TEMPLATE_DB_NAME}
      POSTGRES_USER: ${TEMPLATE_DB_USER}
      POSTGRES_PASSWORD: ${TEMPLATE_DB_PASS}
    ports:
      - "5434:5432" # map container port 5432 to host 5434
    volumes:
      - template_db_data:/var/lib/postgresql/data
    networks:
      - notify_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template_user -d template_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  notify_network:
    driver: bridge

volumes:
  gateway_db_data:
    driver: local
  template_db_data:
    driver: local
